# kubectl apply -f K8s/prometheus.yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  serviceName: "prometheus"
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
          args: ["--config.file=/etc/prometheus/prometheus.yml"]
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    # Your Prometheus configuration here
    global:
      scrape_interval: 10s
    
    scrape_configs:
      - job_name: 'kafka'
        honor_timestamps: true
        static_configs:
          - targets: [ 'kafka:5085' ]
        relabel_configs:
          - source_labels: [ __address__ ]
            target_label: hostname
            regex: '([^:]+)(:[0-9]+)?'
            replacement: '${1}'
      
      - job_name: 'processing_server'
        static_configs:
          - targets: [ 'server-processing:8080' ]

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090


