# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import message.cam_pb2 as cam__pb2


class SubscriptionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCamIds = channel.unary_unary(
                '/message.SubscriptionService/GetCamIds',
                request_serializer=cam__pb2.UserIdRequest.SerializeToString,
                response_deserializer=cam__pb2.CamIdsResponse.FromString,
                )


class SubscriptionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCamIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SubscriptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCamIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCamIds,
                    request_deserializer=cam__pb2.UserIdRequest.FromString,
                    response_serializer=cam__pb2.CamIdsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message.SubscriptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SubscriptionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCamIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.SubscriptionService/GetCamIds',
            cam__pb2.UserIdRequest.SerializeToString,
            cam__pb2.CamIdsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
