# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subscription.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12subscription.proto\x12\x07message\"J\n\x0c\x43\x61mIdRequest\x12\x0e\n\x06\x63\x61m_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x16\n\x0eresponse_topic\x18\x03 \x01(\t\"7\n\x0f\x43hatIdsResponse\x12\x10\n\x08\x63hat_ids\x18\x01 \x03(\x03\x12\x12\n\nrequest_id\x18\x02 \x01(\t2U\n\x14SubscriptionService_\x12=\n\nGetChatIds\x12\x15.message.CamIdRequest\x1a\x18.message.ChatIdsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'subscription_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CAMIDREQUEST']._serialized_start=31
  _globals['_CAMIDREQUEST']._serialized_end=105
  _globals['_CHATIDSRESPONSE']._serialized_start=107
  _globals['_CHATIDSRESPONSE']._serialized_end=162
  _globals['_SUBSCRIPTIONSERVICE_']._serialized_start=164
  _globals['_SUBSCRIPTIONSERVICE_']._serialized_end=249
# @@protoc_insertion_point(module_scope)
