apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Resources section lists all the Kubernetes resources to be managed by Kustomize.
resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
  - ingress.yaml