FROM camcontroller-cpp_dev:latest
RUN apk upgrade
RUN apk add --no-cache ffmpeg curl-dev opencv-dev
RUN apk add --no-cache protobuf-dev libprotobuf protoc
RUN #apk add --no-cache v4l-utils
RUN apk add --no-cache paho-mqtt-c-dev

RUN   apk add git build-base cmake openssl-dev
RUN git clone https://github.com/eclipse/paho.mqtt.cpp.git
WORKDIR /paho.mqtt.cpp
RUN mkdir build
WORKDIR /paho.mqtt.cpp/build
RUN cmake ..
RUN make -j8
RUN make install
WORKDIR /
RUN mkdir app
WORKDIR /app

