apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    labels:
      custom-label: "control-plane"
    ## The following is required to enable ingress on the control-plane node
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 443
        hostPort: 443
        protocol: TCP
        # ingress
      - containerPort: 80
        hostPort: 80
        protocol: TCP
        #kafka
      - containerPort: 30001
        hostPort: 30001
        protocol: TCP
        #rabbitmq
      - containerPort: 30002
        hostPort: 30002
        protocol: TCP
        #mongo
      - containerPort: 30003
        hostPort: 30003
        protocol: TCP
        #minio
      - containerPort: 30004
        hostPort: 30004
        protocol: TCP
  - role: worker
    labels:
      custom-label: "worker"
