apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - StatefulSet/zookeeper.yaml
  - StatefulSet/kafka.yaml
  - StatefulSet/minio.yaml
  - StatefulSet/rabbitmq.yaml
  - StatefulSet/mongodb.yaml
  - StatefulSet/prometheus.yaml
  - Deployment/command_server.yaml
  - Deployment/processing_server.yaml
  - Deployment/auth_server.yaml
  - Deployment/main_server.yaml
  - Deployment/notification_bot.yaml
  - Deployment/conversation_bot.yaml
  - Deployment/sla_manager.yaml
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
  - Deployment/ingress.yaml

