# Dockerfile_GO
FROM golang:1.22rc1 AS go_build_stage
WORKDIR /app

# Copy only the Go module files first
COPY ../GO/go.mod .
COPY ../GO/go.sum .

# Download dependencies
RUN go mod download

# Copy the rest of the application code
COPY ../GO .

WORKDIR /app/src/server_main
RUN go build -o main_server

WORKDIR /app/src/server_command
RUN go build -o command_server

WORKDIR /app/src/server_auth
RUN go build -o auth_server

# Dockerfile_server_command
FROM golang:1.22rc1 as command_server
WORKDIR /app
COPY --from=go_build_stage /app/src/server_command/command_server /app/command_server
CMD ["/app/command_server"]

# Dockerfile_server_main
FROM golang:1.22rc1 as main_server
WORKDIR /app
COPY --from=go_build_stage /app/src/server_main/main_server /app/main_server
COPY --from=go_build_stage /app/src/templates /app/templates
CMD ["/app/main_server"]

# Dockerfile_server_auth
FROM golang:1.22rc1 as auth_server
WORKDIR /app
COPY --from=go_build_stage /app/src/server_auth/auth_server /app/auth_server
COPY --from=go_build_stage /app/src/templates /app/templates
CMD ["/app/auth_server"]