# Use an official Python runtime as a parent image
FROM python:latest as base

# Set the working directory in the container
WORKDIR /app

# Copy the rest of the application code
COPY ../Python/src ./src

FROM base as conversation_bot

RUN mv src/conversation_bot/main.py src/main.py

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r src/conversation_bot/requirements.txt

# Run main.py when the container launches
CMD ["python", "src/main.py"]

FROM base as notification_bot

RUN mv src/notification_bot/main.py src/main.py

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r src/notification_bot/requirements.txt

# Run main.py when the container launches
CMD ["python", "src/main.py"]
