global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: [ 'kafka:9101' ]

  - job_name: 'processing_server'
    static_configs:
      - targets: [ 'server_processing:8080' ]