// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: framedata.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_framedata_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_framedata_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_framedata_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_framedata_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_framedata_2eproto;
namespace my_namespace {
namespace message {
class FrameData;
class FrameDataDefaultTypeInternal;
extern FrameDataDefaultTypeInternal _FrameData_default_instance_;
}  // namespace message
}  // namespace my_namespace
PROTOBUF_NAMESPACE_OPEN
template<> ::my_namespace::message::FrameData* Arena::CreateMaybeMessage<::my_namespace::message::FrameData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace my_namespace {
namespace message {

// ===================================================================

class FrameData PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:my_namespace.message.FrameData) */ {
 public:
  inline FrameData() : FrameData(nullptr) {};
  virtual ~FrameData();

  FrameData(const FrameData& from);
  FrameData(FrameData&& from) noexcept
    : FrameData() {
    *this = ::std::move(from);
  }

  inline FrameData& operator=(const FrameData& from) {
    CopyFrom(from);
    return *this;
  }
  inline FrameData& operator=(FrameData&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FrameData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FrameData* internal_default_instance() {
    return reinterpret_cast<const FrameData*>(
               &_FrameData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FrameData& a, FrameData& b) {
    a.Swap(&b);
  }
  inline void Swap(FrameData* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FrameData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FrameData* New() const final {
    return CreateMaybeMessage<FrameData>(nullptr);
  }

  FrameData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FrameData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FrameData& from);
  void MergeFrom(const FrameData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FrameData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "my_namespace.message.FrameData";
  }
  protected:
  explicit FrameData(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_framedata_2eproto);
    return ::descriptor_table_framedata_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFrameDataFieldNumber = 1,
    kCamIdFieldNumber = 3,
    kTimestampFieldNumber = 2,
  };
  // bytes frame_data = 1;
  void clear_frame_data();
  const std::string& frame_data() const;
  void set_frame_data(const std::string& value);
  void set_frame_data(std::string&& value);
  void set_frame_data(const char* value);
  void set_frame_data(const void* value, size_t size);
  std::string* mutable_frame_data();
  std::string* release_frame_data();
  void set_allocated_frame_data(std::string* frame_data);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_frame_data();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_frame_data(
      std::string* frame_data);
  private:
  const std::string& _internal_frame_data() const;
  void _internal_set_frame_data(const std::string& value);
  std::string* _internal_mutable_frame_data();
  public:

  // string cam_id = 3;
  void clear_cam_id();
  const std::string& cam_id() const;
  void set_cam_id(const std::string& value);
  void set_cam_id(std::string&& value);
  void set_cam_id(const char* value);
  void set_cam_id(const char* value, size_t size);
  std::string* mutable_cam_id();
  std::string* release_cam_id();
  void set_allocated_cam_id(std::string* cam_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_cam_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_cam_id(
      std::string* cam_id);
  private:
  const std::string& _internal_cam_id() const;
  void _internal_set_cam_id(const std::string& value);
  std::string* _internal_mutable_cam_id();
  public:

  // .google.protobuf.Timestamp timestamp = 2;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();

  // @@protoc_insertion_point(class_scope:my_namespace.message.FrameData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr frame_data_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cam_id_;
  PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_framedata_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FrameData

// bytes frame_data = 1;
inline void FrameData::clear_frame_data() {
  frame_data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FrameData::frame_data() const {
  // @@protoc_insertion_point(field_get:my_namespace.message.FrameData.frame_data)
  return _internal_frame_data();
}
inline void FrameData::set_frame_data(const std::string& value) {
  _internal_set_frame_data(value);
  // @@protoc_insertion_point(field_set:my_namespace.message.FrameData.frame_data)
}
inline std::string* FrameData::mutable_frame_data() {
  // @@protoc_insertion_point(field_mutable:my_namespace.message.FrameData.frame_data)
  return _internal_mutable_frame_data();
}
inline const std::string& FrameData::_internal_frame_data() const {
  return frame_data_.Get();
}
inline void FrameData::_internal_set_frame_data(const std::string& value) {
  
  frame_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FrameData::set_frame_data(std::string&& value) {
  
  frame_data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:my_namespace.message.FrameData.frame_data)
}
inline void FrameData::set_frame_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  frame_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:my_namespace.message.FrameData.frame_data)
}
inline void FrameData::set_frame_data(const void* value,
    size_t size) {
  
  frame_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:my_namespace.message.FrameData.frame_data)
}
inline std::string* FrameData::_internal_mutable_frame_data() {
  
  return frame_data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FrameData::release_frame_data() {
  // @@protoc_insertion_point(field_release:my_namespace.message.FrameData.frame_data)
  return frame_data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FrameData::set_allocated_frame_data(std::string* frame_data) {
  if (frame_data != nullptr) {
    
  } else {
    
  }
  frame_data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), frame_data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:my_namespace.message.FrameData.frame_data)
}
inline std::string* FrameData::unsafe_arena_release_frame_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:my_namespace.message.FrameData.frame_data)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return frame_data_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FrameData::unsafe_arena_set_allocated_frame_data(
    std::string* frame_data) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (frame_data != nullptr) {
    
  } else {
    
  }
  frame_data_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      frame_data, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:my_namespace.message.FrameData.frame_data)
}

// .google.protobuf.Timestamp timestamp = 2;
inline bool FrameData::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool FrameData::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& FrameData::_internal_timestamp() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = timestamp_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& FrameData::timestamp() const {
  // @@protoc_insertion_point(field_get:my_namespace.message.FrameData.timestamp)
  return _internal_timestamp();
}
inline void FrameData::unsafe_arena_set_allocated_timestamp(
    PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:my_namespace.message.FrameData.timestamp)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* FrameData::release_timestamp() {
  auto temp = unsafe_arena_release_timestamp();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* FrameData::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:my_namespace.message.FrameData.timestamp)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* FrameData::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArena());
    timestamp_ = p;
  }
  return timestamp_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* FrameData::mutable_timestamp() {
  // @@protoc_insertion_point(field_mutable:my_namespace.message.FrameData.timestamp)
  return _internal_mutable_timestamp();
}
inline void FrameData::set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:my_namespace.message.FrameData.timestamp)
}

// string cam_id = 3;
inline void FrameData::clear_cam_id() {
  cam_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FrameData::cam_id() const {
  // @@protoc_insertion_point(field_get:my_namespace.message.FrameData.cam_id)
  return _internal_cam_id();
}
inline void FrameData::set_cam_id(const std::string& value) {
  _internal_set_cam_id(value);
  // @@protoc_insertion_point(field_set:my_namespace.message.FrameData.cam_id)
}
inline std::string* FrameData::mutable_cam_id() {
  // @@protoc_insertion_point(field_mutable:my_namespace.message.FrameData.cam_id)
  return _internal_mutable_cam_id();
}
inline const std::string& FrameData::_internal_cam_id() const {
  return cam_id_.Get();
}
inline void FrameData::_internal_set_cam_id(const std::string& value) {
  
  cam_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FrameData::set_cam_id(std::string&& value) {
  
  cam_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:my_namespace.message.FrameData.cam_id)
}
inline void FrameData::set_cam_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  cam_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:my_namespace.message.FrameData.cam_id)
}
inline void FrameData::set_cam_id(const char* value,
    size_t size) {
  
  cam_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:my_namespace.message.FrameData.cam_id)
}
inline std::string* FrameData::_internal_mutable_cam_id() {
  
  return cam_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FrameData::release_cam_id() {
  // @@protoc_insertion_point(field_release:my_namespace.message.FrameData.cam_id)
  return cam_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FrameData::set_allocated_cam_id(std::string* cam_id) {
  if (cam_id != nullptr) {
    
  } else {
    
  }
  cam_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), cam_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:my_namespace.message.FrameData.cam_id)
}
inline std::string* FrameData::unsafe_arena_release_cam_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:my_namespace.message.FrameData.cam_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return cam_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FrameData::unsafe_arena_set_allocated_cam_id(
    std::string* cam_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (cam_id != nullptr) {
    
  } else {
    
  }
  cam_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      cam_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:my_namespace.message.FrameData.cam_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace message
}  // namespace my_namespace

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_framedata_2eproto
