// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frameinfo.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_frameinfo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_frameinfo_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_frameinfo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_frameinfo_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_frameinfo_2eproto;
namespace my_namespace {
namespace message {
class FrameInfo;
class FrameInfoDefaultTypeInternal;
extern FrameInfoDefaultTypeInternal _FrameInfo_default_instance_;
}  // namespace message
}  // namespace my_namespace
PROTOBUF_NAMESPACE_OPEN
template<> ::my_namespace::message::FrameInfo* Arena::CreateMaybeMessage<::my_namespace::message::FrameInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace my_namespace {
namespace message {

// ===================================================================

class FrameInfo PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:my_namespace.message.FrameInfo) */ {
 public:
  inline FrameInfo() : FrameInfo(nullptr) {};
  virtual ~FrameInfo();

  FrameInfo(const FrameInfo& from);
  FrameInfo(FrameInfo&& from) noexcept
    : FrameInfo() {
    *this = ::std::move(from);
  }

  inline FrameInfo& operator=(const FrameInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline FrameInfo& operator=(FrameInfo&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FrameInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FrameInfo* internal_default_instance() {
    return reinterpret_cast<const FrameInfo*>(
               &_FrameInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FrameInfo& a, FrameInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(FrameInfo* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FrameInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FrameInfo* New() const final {
    return CreateMaybeMessage<FrameInfo>(nullptr);
  }

  FrameInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FrameInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FrameInfo& from);
  void MergeFrom(const FrameInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FrameInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "my_namespace.message.FrameInfo";
  }
  protected:
  explicit FrameInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_frameinfo_2eproto);
    return ::descriptor_table_frameinfo_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCamIdFieldNumber = 1,
    kTimestampFieldNumber = 2,
    kPersonDetectedFieldNumber = 3,
  };
  // string cam_id = 1;
  void clear_cam_id();
  const std::string& cam_id() const;
  void set_cam_id(const std::string& value);
  void set_cam_id(std::string&& value);
  void set_cam_id(const char* value);
  void set_cam_id(const char* value, size_t size);
  std::string* mutable_cam_id();
  std::string* release_cam_id();
  void set_allocated_cam_id(std::string* cam_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_cam_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_cam_id(
      std::string* cam_id);
  private:
  const std::string& _internal_cam_id() const;
  void _internal_set_cam_id(const std::string& value);
  std::string* _internal_mutable_cam_id();
  public:

  // int64 timestamp = 2;
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // bool personDetected = 3;
  void clear_persondetected();
  bool persondetected() const;
  void set_persondetected(bool value);
  private:
  bool _internal_persondetected() const;
  void _internal_set_persondetected(bool value);
  public:

  // @@protoc_insertion_point(class_scope:my_namespace.message.FrameInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cam_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_;
  bool persondetected_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_frameinfo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FrameInfo

// string cam_id = 1;
inline void FrameInfo::clear_cam_id() {
  cam_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FrameInfo::cam_id() const {
  // @@protoc_insertion_point(field_get:my_namespace.message.FrameInfo.cam_id)
  return _internal_cam_id();
}
inline void FrameInfo::set_cam_id(const std::string& value) {
  _internal_set_cam_id(value);
  // @@protoc_insertion_point(field_set:my_namespace.message.FrameInfo.cam_id)
}
inline std::string* FrameInfo::mutable_cam_id() {
  // @@protoc_insertion_point(field_mutable:my_namespace.message.FrameInfo.cam_id)
  return _internal_mutable_cam_id();
}
inline const std::string& FrameInfo::_internal_cam_id() const {
  return cam_id_.Get();
}
inline void FrameInfo::_internal_set_cam_id(const std::string& value) {
  
  cam_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FrameInfo::set_cam_id(std::string&& value) {
  
  cam_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:my_namespace.message.FrameInfo.cam_id)
}
inline void FrameInfo::set_cam_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  cam_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:my_namespace.message.FrameInfo.cam_id)
}
inline void FrameInfo::set_cam_id(const char* value,
    size_t size) {
  
  cam_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:my_namespace.message.FrameInfo.cam_id)
}
inline std::string* FrameInfo::_internal_mutable_cam_id() {
  
  return cam_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FrameInfo::release_cam_id() {
  // @@protoc_insertion_point(field_release:my_namespace.message.FrameInfo.cam_id)
  return cam_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FrameInfo::set_allocated_cam_id(std::string* cam_id) {
  if (cam_id != nullptr) {
    
  } else {
    
  }
  cam_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), cam_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:my_namespace.message.FrameInfo.cam_id)
}
inline std::string* FrameInfo::unsafe_arena_release_cam_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:my_namespace.message.FrameInfo.cam_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return cam_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FrameInfo::unsafe_arena_set_allocated_cam_id(
    std::string* cam_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (cam_id != nullptr) {
    
  } else {
    
  }
  cam_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      cam_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:my_namespace.message.FrameInfo.cam_id)
}

// int64 timestamp = 2;
inline void FrameInfo::clear_timestamp() {
  timestamp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 FrameInfo::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 FrameInfo::timestamp() const {
  // @@protoc_insertion_point(field_get:my_namespace.message.FrameInfo.timestamp)
  return _internal_timestamp();
}
inline void FrameInfo::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  timestamp_ = value;
}
inline void FrameInfo::set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:my_namespace.message.FrameInfo.timestamp)
}

// bool personDetected = 3;
inline void FrameInfo::clear_persondetected() {
  persondetected_ = false;
}
inline bool FrameInfo::_internal_persondetected() const {
  return persondetected_;
}
inline bool FrameInfo::persondetected() const {
  // @@protoc_insertion_point(field_get:my_namespace.message.FrameInfo.personDetected)
  return _internal_persondetected();
}
inline void FrameInfo::_internal_set_persondetected(bool value) {
  
  persondetected_ = value;
}
inline void FrameInfo::set_persondetected(bool value) {
  _internal_set_persondetected(value);
  // @@protoc_insertion_point(field_set:my_namespace.message.FrameInfo.personDetected)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace message
}  // namespace my_namespace

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_frameinfo_2eproto
