// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CPP.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_CamController_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_CamController_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_CamController_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_CamController_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_CamController_2eproto;
namespace my_namespace {
namespace message {
class Command;
class CommandDefaultTypeInternal;
extern CommandDefaultTypeInternal _Command_default_instance_;
class FrameData;
class FrameDataDefaultTypeInternal;
extern FrameDataDefaultTypeInternal _FrameData_default_instance_;
class Notification;
class NotificationDefaultTypeInternal;
extern NotificationDefaultTypeInternal _Notification_default_instance_;
}  // namespace message
}  // namespace cam_controller
PROTOBUF_NAMESPACE_OPEN
template<> ::my_namespace::message::Command* Arena::CreateMaybeMessage<::my_namespace::message::Command>(Arena*);
template<> ::my_namespace::message::FrameData* Arena::CreateMaybeMessage<::my_namespace::message::FrameData>(Arena*);
template<> ::my_namespace::message::Notification* Arena::CreateMaybeMessage<::my_namespace::message::Notification>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace my_namespace {
namespace message {

// ===================================================================

class FrameData PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cam_controller.message.FrameData) */ {
 public:
  inline FrameData() : FrameData(nullptr) {};
  virtual ~FrameData();

  FrameData(const FrameData& from);
  FrameData(FrameData&& from) noexcept
    : FrameData() {
    *this = ::std::move(from);
  }

  inline FrameData& operator=(const FrameData& from) {
    CopyFrom(from);
    return *this;
  }
  inline FrameData& operator=(FrameData&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FrameData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FrameData* internal_default_instance() {
    return reinterpret_cast<const FrameData*>(
               &_FrameData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FrameData& a, FrameData& b) {
    a.Swap(&b);
  }
  inline void Swap(FrameData* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FrameData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FrameData* New() const final {
    return CreateMaybeMessage<FrameData>(nullptr);
  }

  FrameData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FrameData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FrameData& from);
  void MergeFrom(const FrameData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FrameData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cam_controller.message.FrameData";
  }
  protected:
  explicit FrameData(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_CamController_2eproto);
    return ::descriptor_table_CamController_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFrameDataFieldNumber = 2,
    kTimestampFieldNumber = 1,
    kPersonDetectedFieldNumber = 3,
  };
  // bytes frame_data = 2;
  void clear_frame_data();
  const std::string& frame_data() const;
  void set_frame_data(const std::string& value);
  void set_frame_data(std::string&& value);
  void set_frame_data(const char* value);
  void set_frame_data(const void* value, size_t size);
  std::string* mutable_frame_data();
  std::string* release_frame_data();
  void set_allocated_frame_data(std::string* frame_data);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_frame_data();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_frame_data(
      std::string* frame_data);
  private:
  const std::string& _internal_frame_data() const;
  void _internal_set_frame_data(const std::string& value);
  std::string* _internal_mutable_frame_data();
  public:

  // .google.protobuf.Timestamp timestamp = 1;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();

  // bool person_detected = 3;
  void clear_person_detected();
  bool person_detected() const;
  void set_person_detected(bool value);
  private:
  bool _internal_person_detected() const;
  void _internal_set_person_detected(bool value);
  public:

  // @@protoc_insertion_point(class_scope:cam_controller.message.FrameData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr frame_data_;
  PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
  bool person_detected_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CamController_2eproto;
};
// -------------------------------------------------------------------

class Command PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cam_controller.message.Command) */ {
 public:
  inline Command() : Command(nullptr) {};
  virtual ~Command();

  Command(const Command& from);
  Command(Command&& from) noexcept
    : Command() {
    *this = ::std::move(from);
  }

  inline Command& operator=(const Command& from) {
    CopyFrom(from);
    return *this;
  }
  inline Command& operator=(Command&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Command& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Command* internal_default_instance() {
    return reinterpret_cast<const Command*>(
               &_Command_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Command& a, Command& b) {
    a.Swap(&b);
  }
  inline void Swap(Command* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Command* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Command* New() const final {
    return CreateMaybeMessage<Command>(nullptr);
  }

  Command* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Command>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Command& from);
  void MergeFrom(const Command& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Command* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cam_controller.message.Command";
  }
  protected:
  explicit Command(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_CamController_2eproto);
    return ::descriptor_table_CamController_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kParametersFieldNumber = 3,
    kCommandTypeFieldNumber = 2,
    kTimestampFieldNumber = 4,
    kCommandIdFieldNumber = 1,
  };
  // repeated string parameters = 3;
  int parameters_size() const;
  private:
  int _internal_parameters_size() const;
  public:
  void clear_parameters();
  const std::string& parameters(int index) const;
  std::string* mutable_parameters(int index);
  void set_parameters(int index, const std::string& value);
  void set_parameters(int index, std::string&& value);
  void set_parameters(int index, const char* value);
  void set_parameters(int index, const char* value, size_t size);
  std::string* add_parameters();
  void add_parameters(const std::string& value);
  void add_parameters(std::string&& value);
  void add_parameters(const char* value);
  void add_parameters(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& parameters() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_parameters();
  private:
  const std::string& _internal_parameters(int index) const;
  std::string* _internal_add_parameters();
  public:

  // string command_type = 2;
  void clear_command_type();
  const std::string& command_type() const;
  void set_command_type(const std::string& value);
  void set_command_type(std::string&& value);
  void set_command_type(const char* value);
  void set_command_type(const char* value, size_t size);
  std::string* mutable_command_type();
  std::string* release_command_type();
  void set_allocated_command_type(std::string* command_type);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_command_type();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_command_type(
      std::string* command_type);
  private:
  const std::string& _internal_command_type() const;
  void _internal_set_command_type(const std::string& value);
  std::string* _internal_mutable_command_type();
  public:

  // .google.protobuf.Timestamp timestamp = 4;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();

  // int32 command_id = 1;
  void clear_command_id();
  ::PROTOBUF_NAMESPACE_ID::int32 command_id() const;
  void set_command_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_command_id() const;
  void _internal_set_command_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:cam_controller.message.Command)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> parameters_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr command_type_;
  PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
  ::PROTOBUF_NAMESPACE_ID::int32 command_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CamController_2eproto;
};
// -------------------------------------------------------------------

class Notification PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cam_controller.message.Notification) */ {
 public:
  inline Notification() : Notification(nullptr) {};
  virtual ~Notification();

  Notification(const Notification& from);
  Notification(Notification&& from) noexcept
    : Notification() {
    *this = ::std::move(from);
  }

  inline Notification& operator=(const Notification& from) {
    CopyFrom(from);
    return *this;
  }
  inline Notification& operator=(Notification&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Notification& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Notification* internal_default_instance() {
    return reinterpret_cast<const Notification*>(
               &_Notification_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Notification& a, Notification& b) {
    a.Swap(&b);
  }
  inline void Swap(Notification* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Notification* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Notification* New() const final {
    return CreateMaybeMessage<Notification>(nullptr);
  }

  Notification* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Notification>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Notification& from);
  void MergeFrom(const Notification& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Notification* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cam_controller.message.Notification";
  }
  protected:
  explicit Notification(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_CamController_2eproto);
    return ::descriptor_table_CamController_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCamIdFieldNumber = 1,
    kTimestampFieldNumber = 2,
  };
  // string cam_id = 1;
  void clear_cam_id();
  const std::string& cam_id() const;
  void set_cam_id(const std::string& value);
  void set_cam_id(std::string&& value);
  void set_cam_id(const char* value);
  void set_cam_id(const char* value, size_t size);
  std::string* mutable_cam_id();
  std::string* release_cam_id();
  void set_allocated_cam_id(std::string* cam_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_cam_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_cam_id(
      std::string* cam_id);
  private:
  const std::string& _internal_cam_id() const;
  void _internal_set_cam_id(const std::string& value);
  std::string* _internal_mutable_cam_id();
  public:

  // .google.protobuf.Timestamp timestamp = 2;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();

  // @@protoc_insertion_point(class_scope:cam_controller.message.Notification)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cam_id_;
  PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CamController_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FrameData

// .google.protobuf.Timestamp timestamp = 1;
inline bool FrameData::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool FrameData::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& FrameData::_internal_timestamp() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = timestamp_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& FrameData::timestamp() const {
  // @@protoc_insertion_point(field_get:cam_controller.message.FrameData.timestamp)
  return _internal_timestamp();
}
inline void FrameData::unsafe_arena_set_allocated_timestamp(
    PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cam_controller.message.FrameData.timestamp)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* FrameData::release_timestamp() {
  auto temp = unsafe_arena_release_timestamp();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* FrameData::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:cam_controller.message.FrameData.timestamp)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* FrameData::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArena());
    timestamp_ = p;
  }
  return timestamp_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* FrameData::mutable_timestamp() {
  // @@protoc_insertion_point(field_mutable:cam_controller.message.FrameData.timestamp)
  return _internal_mutable_timestamp();
}
inline void FrameData::set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:cam_controller.message.FrameData.timestamp)
}

// bytes frame_data = 2;
inline void FrameData::clear_frame_data() {
  frame_data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FrameData::frame_data() const {
  // @@protoc_insertion_point(field_get:cam_controller.message.FrameData.frame_data)
  return _internal_frame_data();
}
inline void FrameData::set_frame_data(const std::string& value) {
  _internal_set_frame_data(value);
  // @@protoc_insertion_point(field_set:cam_controller.message.FrameData.frame_data)
}
inline std::string* FrameData::mutable_frame_data() {
  // @@protoc_insertion_point(field_mutable:cam_controller.message.FrameData.frame_data)
  return _internal_mutable_frame_data();
}
inline const std::string& FrameData::_internal_frame_data() const {
  return frame_data_.Get();
}
inline void FrameData::_internal_set_frame_data(const std::string& value) {
  
  frame_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FrameData::set_frame_data(std::string&& value) {
  
  frame_data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:cam_controller.message.FrameData.frame_data)
}
inline void FrameData::set_frame_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  frame_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:cam_controller.message.FrameData.frame_data)
}
inline void FrameData::set_frame_data(const void* value,
    size_t size) {
  
  frame_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:cam_controller.message.FrameData.frame_data)
}
inline std::string* FrameData::_internal_mutable_frame_data() {
  
  return frame_data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FrameData::release_frame_data() {
  // @@protoc_insertion_point(field_release:cam_controller.message.FrameData.frame_data)
  return frame_data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FrameData::set_allocated_frame_data(std::string* frame_data) {
  if (frame_data != nullptr) {
    
  } else {
    
  }
  frame_data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), frame_data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:cam_controller.message.FrameData.frame_data)
}
inline std::string* FrameData::unsafe_arena_release_frame_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:cam_controller.message.FrameData.frame_data)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return frame_data_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FrameData::unsafe_arena_set_allocated_frame_data(
    std::string* frame_data) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (frame_data != nullptr) {
    
  } else {
    
  }
  frame_data_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      frame_data, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cam_controller.message.FrameData.frame_data)
}

// bool person_detected = 3;
inline void FrameData::clear_person_detected() {
  person_detected_ = false;
}
inline bool FrameData::_internal_person_detected() const {
  return person_detected_;
}
inline bool FrameData::person_detected() const {
  // @@protoc_insertion_point(field_get:cam_controller.message.FrameData.person_detected)
  return _internal_person_detected();
}
inline void FrameData::_internal_set_person_detected(bool value) {
  
  person_detected_ = value;
}
inline void FrameData::set_person_detected(bool value) {
  _internal_set_person_detected(value);
  // @@protoc_insertion_point(field_set:cam_controller.message.FrameData.person_detected)
}

// -------------------------------------------------------------------

// Command

// int32 command_id = 1;
inline void Command::clear_command_id() {
  command_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Command::_internal_command_id() const {
  return command_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Command::command_id() const {
  // @@protoc_insertion_point(field_get:cam_controller.message.Command.command_id)
  return _internal_command_id();
}
inline void Command::_internal_set_command_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  command_id_ = value;
}
inline void Command::set_command_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_command_id(value);
  // @@protoc_insertion_point(field_set:cam_controller.message.Command.command_id)
}

// string command_type = 2;
inline void Command::clear_command_type() {
  command_type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Command::command_type() const {
  // @@protoc_insertion_point(field_get:cam_controller.message.Command.command_type)
  return _internal_command_type();
}
inline void Command::set_command_type(const std::string& value) {
  _internal_set_command_type(value);
  // @@protoc_insertion_point(field_set:cam_controller.message.Command.command_type)
}
inline std::string* Command::mutable_command_type() {
  // @@protoc_insertion_point(field_mutable:cam_controller.message.Command.command_type)
  return _internal_mutable_command_type();
}
inline const std::string& Command::_internal_command_type() const {
  return command_type_.Get();
}
inline void Command::_internal_set_command_type(const std::string& value) {
  
  command_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Command::set_command_type(std::string&& value) {
  
  command_type_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:cam_controller.message.Command.command_type)
}
inline void Command::set_command_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  command_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:cam_controller.message.Command.command_type)
}
inline void Command::set_command_type(const char* value,
    size_t size) {
  
  command_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:cam_controller.message.Command.command_type)
}
inline std::string* Command::_internal_mutable_command_type() {
  
  return command_type_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Command::release_command_type() {
  // @@protoc_insertion_point(field_release:cam_controller.message.Command.command_type)
  return command_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Command::set_allocated_command_type(std::string* command_type) {
  if (command_type != nullptr) {
    
  } else {
    
  }
  command_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), command_type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:cam_controller.message.Command.command_type)
}
inline std::string* Command::unsafe_arena_release_command_type() {
  // @@protoc_insertion_point(field_unsafe_arena_release:cam_controller.message.Command.command_type)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return command_type_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Command::unsafe_arena_set_allocated_command_type(
    std::string* command_type) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (command_type != nullptr) {
    
  } else {
    
  }
  command_type_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      command_type, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cam_controller.message.Command.command_type)
}

// repeated string parameters = 3;
inline int Command::_internal_parameters_size() const {
  return parameters_.size();
}
inline int Command::parameters_size() const {
  return _internal_parameters_size();
}
inline void Command::clear_parameters() {
  parameters_.Clear();
}
inline std::string* Command::add_parameters() {
  // @@protoc_insertion_point(field_add_mutable:cam_controller.message.Command.parameters)
  return _internal_add_parameters();
}
inline const std::string& Command::_internal_parameters(int index) const {
  return parameters_.Get(index);
}
inline const std::string& Command::parameters(int index) const {
  // @@protoc_insertion_point(field_get:cam_controller.message.Command.parameters)
  return _internal_parameters(index);
}
inline std::string* Command::mutable_parameters(int index) {
  // @@protoc_insertion_point(field_mutable:cam_controller.message.Command.parameters)
  return parameters_.Mutable(index);
}
inline void Command::set_parameters(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:cam_controller.message.Command.parameters)
  parameters_.Mutable(index)->assign(value);
}
inline void Command::set_parameters(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:cam_controller.message.Command.parameters)
  parameters_.Mutable(index)->assign(std::move(value));
}
inline void Command::set_parameters(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  parameters_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:cam_controller.message.Command.parameters)
}
inline void Command::set_parameters(int index, const char* value, size_t size) {
  parameters_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:cam_controller.message.Command.parameters)
}
inline std::string* Command::_internal_add_parameters() {
  return parameters_.Add();
}
inline void Command::add_parameters(const std::string& value) {
  parameters_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:cam_controller.message.Command.parameters)
}
inline void Command::add_parameters(std::string&& value) {
  parameters_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:cam_controller.message.Command.parameters)
}
inline void Command::add_parameters(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  parameters_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:cam_controller.message.Command.parameters)
}
inline void Command::add_parameters(const char* value, size_t size) {
  parameters_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:cam_controller.message.Command.parameters)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Command::parameters() const {
  // @@protoc_insertion_point(field_list:cam_controller.message.Command.parameters)
  return parameters_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Command::mutable_parameters() {
  // @@protoc_insertion_point(field_mutable_list:cam_controller.message.Command.parameters)
  return &parameters_;
}

// .google.protobuf.Timestamp timestamp = 4;
inline bool Command::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool Command::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& Command::_internal_timestamp() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = timestamp_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& Command::timestamp() const {
  // @@protoc_insertion_point(field_get:cam_controller.message.Command.timestamp)
  return _internal_timestamp();
}
inline void Command::unsafe_arena_set_allocated_timestamp(
    PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cam_controller.message.Command.timestamp)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Command::release_timestamp() {
  auto temp = unsafe_arena_release_timestamp();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Command::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:cam_controller.message.Command.timestamp)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Command::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArena());
    timestamp_ = p;
  }
  return timestamp_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Command::mutable_timestamp() {
  // @@protoc_insertion_point(field_mutable:cam_controller.message.Command.timestamp)
  return _internal_mutable_timestamp();
}
inline void Command::set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:cam_controller.message.Command.timestamp)
}

// -------------------------------------------------------------------

// Notification

// string cam_id = 1;
inline void Notification::clear_cam_id() {
  cam_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Notification::cam_id() const {
  // @@protoc_insertion_point(field_get:cam_controller.message.Notification.cam_id)
  return _internal_cam_id();
}
inline void Notification::set_cam_id(const std::string& value) {
  _internal_set_cam_id(value);
  // @@protoc_insertion_point(field_set:cam_controller.message.Notification.cam_id)
}
inline std::string* Notification::mutable_cam_id() {
  // @@protoc_insertion_point(field_mutable:cam_controller.message.Notification.cam_id)
  return _internal_mutable_cam_id();
}
inline const std::string& Notification::_internal_cam_id() const {
  return cam_id_.Get();
}
inline void Notification::_internal_set_cam_id(const std::string& value) {
  
  cam_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Notification::set_cam_id(std::string&& value) {
  
  cam_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:cam_controller.message.Notification.cam_id)
}
inline void Notification::set_cam_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  cam_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:cam_controller.message.Notification.cam_id)
}
inline void Notification::set_cam_id(const char* value,
    size_t size) {
  
  cam_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:cam_controller.message.Notification.cam_id)
}
inline std::string* Notification::_internal_mutable_cam_id() {
  
  return cam_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Notification::release_cam_id() {
  // @@protoc_insertion_point(field_release:cam_controller.message.Notification.cam_id)
  return cam_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Notification::set_allocated_cam_id(std::string* cam_id) {
  if (cam_id != nullptr) {
    
  } else {
    
  }
  cam_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), cam_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:cam_controller.message.Notification.cam_id)
}
inline std::string* Notification::unsafe_arena_release_cam_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:cam_controller.message.Notification.cam_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return cam_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Notification::unsafe_arena_set_allocated_cam_id(
    std::string* cam_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (cam_id != nullptr) {
    
  } else {
    
  }
  cam_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      cam_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cam_controller.message.Notification.cam_id)
}

// .google.protobuf.Timestamp timestamp = 2;
inline bool Notification::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool Notification::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& Notification::_internal_timestamp() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = timestamp_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& Notification::timestamp() const {
  // @@protoc_insertion_point(field_get:cam_controller.message.Notification.timestamp)
  return _internal_timestamp();
}
inline void Notification::unsafe_arena_set_allocated_timestamp(
    PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cam_controller.message.Notification.timestamp)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Notification::release_timestamp() {
  auto temp = unsafe_arena_release_timestamp();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Notification::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:cam_controller.message.Notification.timestamp)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Notification::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArena());
    timestamp_ = p;
  }
  return timestamp_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Notification::mutable_timestamp() {
  // @@protoc_insertion_point(field_mutable:cam_controller.message.Notification.timestamp)
  return _internal_mutable_timestamp();
}
inline void Notification::set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:cam_controller.message.Notification.timestamp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace message
}  // namespace cam_controller

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_CamController_2eproto
