apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Resources section lists all the Kubernetes resources to be managed by Kustomize.
resources:
  - processing_server.yaml
  - auth_server.yaml
  - command_server.yaml
  - main_server.yaml
  - notification_bot.yaml
  - conversation_bot.yaml
  - sla_manager.yaml

